import{a as L,S as b,i as w}from"./assets/vendor-c145bea9.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const v=document.querySelector(".form"),i=document.querySelector(".gallery"),u=document.querySelector(".loader"),c=document.querySelector(".load-more-btn");let n={key:"41631198-f5cd04d694ed896bf4215baa6",image_type:"photo",orientation:"horizontal",safesearch:!0,page:1,per_page:40},d;function x(){u.style.display="block",i.style.display="none",c.style.display="none"}function S(t){u.style.display="none",i.style.display="flex",c.style.display=t?"block":"none"}function p(t){return t.reduce((a,o)=>{const{largeImageURL:s,webformatURL:e,tags:r,likes:l,views:g,comments:m,downloads:h}=o;return a+`<li class="gallery-item">
        <a href=${s}> 
          <img class="gallery-img" src=${e} alt=${r} />
        </a>
        <div class="gallery-text-box">
          <p>Likes: <span class="text-value">${l}</span></p>
          <p>views: <span class="text-value">${g}</span></p>
          <p>comments: <span class="text-value">${m}</span></p>
          <p>downloads: <span class="text-value">${h}</span></p>
        </div>
      </li>`},"")}function T(t){const a=p(t);i.innerHTML=a}function q(t){const a=p(t);i.innerHTML+=a,y()}function y(){d||(d=new b(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0})),d.refresh()}function $(){i.style.display="none",w.error({position:"topRight",color:"red",message:"Sorry, there are no images matching your search query. Please try again!"})}async function f(t,a=!1){a||x();try{const o=await L.get(`https://pixabay.com/api/?${t}`);if(S(o.data.hits.length>=n.per_page),o.status!==200)throw new Error(o.statusText);const{hits:s}=o.data;s.length>0?(a?q(s):T(s),y()):$(),c.style.display=s.length>=n.per_page?"block":"none"}catch(o){console.error(o)}}v.addEventListener("submit",async t=>{t.preventDefault(),n.q=t.target.elements.search.value.trim(),n.q,n.page=1,await f(new URLSearchParams(n)),t.currentTarget.reset()});c.addEventListener("click",async()=>{n.page++,await f(new URLSearchParams(n),!0)});c.style.display="none";
//# sourceMappingURL=commonHelpers.js.map
